Fixed variable scoping in script and added help message

diff --git a/multiget b/multiget
--- a/multiget
+++ b/multiget
@@ -2,13 +2,12 @@
 
 function display_error
 {
-    name=`echo "$1" | sed 's|^.*/||'`
-    if [[ "$2" == "--no-file" ]]
+    if [[ "$1" == "no-file" ]]
     then
-        echo -e "${name}: error: ${3}: No such file" 1>&2
-    elif [[ "$2" == "--wget-fail" ]]
+        echo -e "${name}: error: ${2}: No such file" 1>&2
+    elif [[ "$1" == "wget-fail" ]]
     then
-        echo -e "${name}: error: URL:${3}: Download failed" 1>&2
+        echo '['`date +"%F %T"`']' "Error:" "URL:${2}:" "Download failed" 1>&2
     else
         echo -e "${name}: fatal error!\n\n"\
                 "\bTry \`$name --help' for more information." 1>&2
@@ -18,14 +17,15 @@ function display_error
 
 function display_help
 {
-    echo "You came here expecting help, but all you receive is sadness."
-    ## TODO: Actual help mode. Add more options to script.
+    echo -e "Usage: $name [listfile]..."
     exit
 }
 
+name=`echo "$0" | sed 's|^.*/||'`
+
 if [ $# -eq 0 ]
 then
-    display_error "$0"
+    display_error
 fi
 
 failure=false
@@ -36,13 +36,13 @@ do
         display_help
     elif ! [ -f "$file" ]
     then
-        display_error "$0" "--no-file" "$file"
+        display_error "no-file" "$file"
         failure=true
     fi
 done
 if $failure
 then
-    display_error "$0"
+    display_error
 fi
 
 for file in "$@"
@@ -60,13 +60,13 @@ do
                     echo '['`date +"%F %T"`']' "Begin:" "URL:${array[0]}" '->' "${array[1]}" 1>&2
                     wget -qN "${array[0]}" -O "${array[1]}" \
                     && echo '['`date +"%F %T"`']' "Finish:" "URL:${array[0]}" 1>&2 \
-                    || display_error "$0" "--wget-fail" "${array[0]}" &
+                    || display_error "$0" "wget-fail" "${array[0]}" &
                 else
-                    name=`echo "$line" | sed 's|^.*/||'`
-                    echo '['`date +"%F %T"`']' "Begin:" "URL:$line" '->' "$name" 1>&2
-                    wget -qN "$line" -O "$name" \
+                    oname=`echo "$line" | sed 's|^.*/||'`
+                    echo '['`date +"%F %T"`']' "Begin:" "URL:$line" '->' "$oname" 1>&2
+                    wget -qN "$line" -O "$oname" \
                     && echo '['`date +"%F %T"`']' "Finish:" "URL:$line" 1>&2 \
-                    || display_error "$0" "--wget-fail" "$line" &
+                    || display_error "$0" "wget-fail" "$line" &
                 fi
             fi
         fi
